### PR TITLE
Completion status harmonisation

### LINKED ISSUE #97: [BUG] Overall score is > 100%
**Describe the bug**
Overall score is > 100%

**To Reproduce**
Go to dashboard

**Expected behavior**
I suppose the maximum overall score is 100%.
It would be helpful to share how to calculate it.

**Screenshots**

image

### LINKED ISSUE #130: [BUG] Additional assessment criteria cannot be removed
**Describe the bug**
Additional assessment criteria cannot be removed

It looks like a portfolio is removed instead of an additional assessment criteria.
Besides, initiatives page cannot show any initiative after removing a portfolio.

**To Reproduce**
Login > My Institution > ADDITIONAL ASSESSMENT CRITERIA > click "REMOVE" button of a criteria > Click "Confirm Remove" button

**Expected behavior**
The selected criteria has been removed

**Screenshots**

image

image

image

image

---

Reference:
image

### PR DESCRIPTION
**Pull request by dave-mills**
Thie PR fixes #97. It also addresses some minor issues with the additional criteria status (#127)

- now the overall_rating in the main dashboard uses $assessment->principle_status for *both* total score and total count.
- The code to show or hide the "additional assessment" parts in the main initiatives list page is updated to check `$organisation->has_additional_criteria`. 

## EDIT ## 
Fixes #130

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I performed some testings.

CASE 1, success

SETTINGS > This Institution uses additional assessment criteria is TICKED
AND
User has defined additional assessment criteria

Then "Assess Additional Criteria" button is showed

image

image

image

**Comment by dan-tang-ssd** [comment]
CASE 2, success

SETTINGS > This Institution uses additional assessment criteria is UNTICKED
AND
User has defined additional assessment criteria

Then "Assess Additional Criteria" button is not showed

image

image

**Comment by dan-tang-ssd** [comment]
CASE 3, TBC

SETTINGS > This Institution uses additional assessment criteria is TICKED
AND
User has not defined additional assessment criteria

When I delete additioanl assessment, it seems like removed portfolio instead... and error occurred...

image

image

image

I realised that portfolio "Example Portfolio 1" (id: 1) is deleted.
After that, initiatives page cannot show initiatives.
I suspect that some initiatives belong to the removed portfolio. And that portfolio cannot be found when preparing initiative details (it shows the portfolio that it belongs to in front end).

image

image

**Comment by dave-mills** [comment]
> I realised that portfolio "Example Portfolio 1" (id: 1) is deleted.
> After that, initiatives page cannot show initiatives.
> I suspect that some initiatives belong to the removed portfolio. And that portfolio cannot be found when preparing initiative details (it shows the portfolio that it belongs to in front end).

Sounds like 2 issues. here:

1. Additional Criteria deletion is mixed up with portfolio deletion routes;
2. When a portfolio is deleted, all initiatives within the portfolio should *also* be deleted, but this is not currently happening. 

I'll fix 1 here, and add 2 to the list.

**Comment by dave-mills** [comment]
@dan-tang-ssd - I've updated the portfolio and additional criteria deletion methods so that:

- now the additional criteria deletion points to the correct method;
- The default backpack CRUD `destroy` method is designed for AJAX, so it was not redirecting back to the main page after compltion. I fixed that by overriting those methods in the 2 CRUD controllers.

**Comment by dan-tang-ssd** [comment]
Just pulled latest code and performed testing in local env.
It does not delete portfolio now, but it also does not delete the additional assessment criteria...
Not sure whether it is related to the score tags related to this criteria...

Remove, Confirm Remove
image

Notification showed
image

The criteria is still here...
image

Score tags related to this criteria
image

**Comment by dave-mills** [comment]
>  It does not delete portfolio now, but it also does not delete the additional assessment criteria...

Fixed

**Comment by dave-mills** [comment]
> When removing additional criteria with score tag, error occurred...

Looks like we missed a cascadeOnDelete option! I've added it in here, and checked that I can delete an additional criteria item with score tags.

**Comment by dave-mills** [comment]
> Found a little issue.
> I created a new additional criteria with score tag. The score tag is saved and can be showed properly. But in additional assessment, the score tag cannot be showed in front end...

@dan-tang-ssd  Is this directly releated to this PR? Or can we merge this in and add this issue to the list?

**Comment by dan-tang-ssd** [comment]
> > Found a little issue.
> > I created a new additional criteria with score tag. The score tag is saved and can be showed properly. But in additional assessment, the score tag cannot be showed in front end...
> 
> @dan-tang-ssd Is this directly releated to this PR? Or can we merge this in and add this issue to the list?

Good suggestions~ Let's merge this PR and add a new issue.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
