### PR TITLE
Add Browsershot

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted for adding browsershot, which is a package to print web page as a PDF file.

Just created a simple Command class for testing.
Below URL shows a spider chart in browser, but it is a login page in the generated PDF file...
http://aec.test/admin/organisation/2/portfolio

image

image

[portfolio_01.pdf](https://github.com/stats4sd/aec_portfolio/files/11478583/portfolio_01.pdf)
[portfolio_02.pdf](https://github.com/stats4sd/aec_portfolio/files/11478584/portfolio_02.pdf)

The current challenge is how to print web page as a logged in user...
I will do more testing and update status.

### CODE REVIEW

**Review by dave-mills — COMMENTED** [review]
Oh, interesting - yeah, I guess it's making a separate http request to the url that isn't part of the current browser session. Which makes sense, given it's using a headless version of Chrome to 'fake' the browser experience and generate the output to be printed, meaning it's totally separate to the current user's session. 

Maybe there's something we can do with custom headers to let browsershot through the authentication, but it doesn't look like it lets you directly hook into an existing user's session, so we'd need to do that within the function and then somehow send the required filters / information to Browsershot.  But that might get complicated enough that it's worth us finding a different solution....

...let me know how your exploration goes!

**Comment by dan-tang-ssd** [comment]
I was thinking whether I can send the request via HTTP so Browsershot can use the same session...
I created a Controller class to generate PDF file, but failed with below error messages found in laravel log file...

It looks strange as I can run the same code in Command class but it throws error in Controller class....
Anyway, seems not worthy to spend time to resolve it at this moment...

---

[2023-05-15 14:12:47] local.DEBUG: GeneratePdfFileController.generatePdfFile()...  
[2023-05-15 14:12:47] local.DEBUG: The command "node ^"C:^\public^\aec^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"http:^\/^\/aec.test^\/admin^\/organisation^\/2^\/portfolio^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"path^\^":^\^"c:^\^\temp^\^\portfolio_01.pdf^\^",^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^}^}^}^"" failed.

Exit Code: 1(General error)

Working directory: C:\public\aec\public

Output:
================


Error Output:
================
[1m[43m[30m
  Puppeteer old Headless deprecation warning:[0m[33m
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m

Error: Could not find Chrome (ver. 113.0.5672.63). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Windows\system32\config\systemprofile\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (C:\public\aec\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:301:27)
    at ChromeLauncher.executablePath (C:\public\aec\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:182:25)
    at ChromeLauncher.computeLaunchArguments (C:\public\aec\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:98:37)
    at async ChromeLauncher.launch (C:\public\aec\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:83:28)
    at async callChrome (C:\public\aec\vendor\spatie\browsershot\bin\browser.js:84:23)

---

Just notice that Browsershot can accept HTML content to generate PDF file.
image

Um.... will below idea too complicated?
If it works, we can almost use it anywhere requires PDF printing.

1. Develop a controller class, accept URL as function parameter
2. Send a HTTP request to the URL, store the HTTP response (Can we assume it is using the same logged in session?)
3. Pass the HTML content to Browsershot, generate HTML

**Comment by dan-tang-ssd** [comment]
I spent much time on trying Browsershot setCookies() function, but not working...
Finally I used a Laravel (um... should be PHP) way to visit a web site with logged in session. 
I get the URL that sent request from HTTP header "referer", so the controller is generic for any web page.
We can simply add a HTML FORM with a submit button to generate PDF in any web page.
I have updated portfolio show page and project show page, it works well.

Regarding PDF file generation, we need to be aware for below items:
1. The generated PDF content looks a bit different from what we see in browser. Particularly the spider chart looks much smaller in PDF file.
2. For tabbed page in a web page, no matter which tabbed page you are viewing in browser, only the first tabbed page will be rendered in PDF file.
3. It would be better to save the generated PDF file in user's computer instead of showing PDF file content directly in browser.

**Review by dave-mills — APPROVED** [review]
Re: browsershot cache - I think you're right that it's a Windows-specific thing. When i deleted the .puppeteerrc.cjs file, I got the pdf to generate ok. The default cacheDirectory = `path.join(os.homedir(), '.cache', 'puppeteer')`. I suspect the os.homedir() is a unix thing...


It's unfortunate that this hasn't been the "easy to drop in" solution I was hoping, but it does seem to have yielded some interesting things. (that might be useful in future projects too...).

To confirm, with this we can add a button on any page to send that page (as the logged-in user sees it) to the `generatePdfFile` method and get a pdf of it - which is great!

One note - for some reason, the pdfs that I generate are all very pale - the transparency is set super high and I'm not sure why: 

[generatePdf.pdf](https://github.com/stats4sd/aec_portfolio/files/11516077/generatePdf.pdf)

Which is odd given that your pdf outputs looked fine, colour-wise. 

So there's probably some tweaking needed on the settings, But layout-wise it does look much better than the default "print" option via the browser, so that's good. For now, I suggest that we include this, and then we can tweak the settings / fix the styling of the outputs when we get to the point of having the real pages ready.

**Comment by dan-tang-ssd** [comment]
> To confirm, with this we can add a button on any page to send that page (as the logged-in user sees it) to the `generatePdfFile` method and get a pdf of it - which is great!

Yes, I confirm.

 
> One note - for some reason, the pdfs that I generate are all very pale - the transparency is set super high and I'm not sure why:
> 
> [generatePdf.pdf](https://github.com/stats4sd/aec_portfolio/files/11516077/generatePdf.pdf)
> 
> Which is odd given that your pdf outputs looked fine, colour-wise.

Oops.... maybe we need to run it on Linux and see what will happen...

> So there's probably some tweaking needed on the settings, But layout-wise it does look much better than the default "print" option via the browser, so that's good. For now, I suggest that we include this, and then we can tweak the settings / fix the styling of the outputs when we get to the point of having the real pages ready.

Yes. I think it is something that we have to do soon.

I have drafted the chart layout for principles summary. It makes use of flot library stacked bar chart. This is what we used in our company web site project management section. I would like to setup it in aec project, generate pdf file and see how it will look.

**Pull request merged**
