### PR TITLE
Add Admin Panel

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is not yet ready for review. It is submitted as a status update.

Added "Admin Panel" in top menu bar. It will be showed for site admin and site manager only. (for those who can maintain institutions)
image

Click "Admin Panel", it will show admin panel menu
image

Click admin panel menu item, it will show corresponding CRUD panel
image

---

Question:
I am thinking whether we should show current admin panel menu items as a side bar at left hand side. 
When user click admin panel menu item, the corresponding CRUD panel will be showed at right hand side.
i.e. the same way as the original backpack dashboard.

Pros: Better navigation, user can manage different items more easily. The sidebar shows an overview for available items.
Cons: For institutional users, there is no sidebar in other CRUD panels. Will it look inconsistent with them?

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Question:
In Role Invite CRUD panel, it shows all invitations.
Should we only show invitation sent for site admin and site manager?

image

**Comment by dan-tang-ssd** [comment]
Question:

Should we expose Institition types, Initaitive categories, Feedback types CRUD panel to site admin and site manager?

image

image

image

image

**Comment by dan-tang-ssd** [comment]
We have a very little chance to add / delete red flags and principles.
In case we need to add new red flags and principles, is program change required?

In ProjectCrudController.php, we have fetchCustomScoreTags1() to fetchCustomScoreTags13(). They look related to principles 1-13. We may need to add fetchCustomScoreTags14() when we have a new principle.

image

image

image

**Comment by dave-mills** [comment]
> Question:
> I am thinking whether we should show current admin panel menu items as a side bar at left hand side. When user click admin panel menu item, the corresponding CRUD panel will be showed at right hand side. i.e. the same way as the original backpack dashboard.

> Pros: Better navigation, user can manage different items more easily. The sidebar shows an overview for available items.
> Cons: For institutional users, there is no sidebar in other CRUD panels. Will it look inconsistent with them?

I think having a visual distinction between the "front end" (all the currently available pages) and the "back end" (the CRUD panels) is a good thing, so I think yes - keep the sidebar for these site-level CRUD panels. 


> Question:
> In Role Invite CRUD panel, it shows all invitations.
> Should we only show invitation sent for site admin and site manager?

I just refreshed my memory of what happens with invites. When someone is invited to join an institution, they get a regular Invite *and* a RoleInvite, so when they register they join with the correct institution *and* role assigned. So these institutional role invites are essentially duplicates... so I think you're right - we don't need to show them here. 

> Should we expose Institition types, Initaitive categories, Feedback types CRUD panel to site admin and site manager?

- Institution types + initiative categories = yes. 
  - These might get updated in future, and I'd like that to be possible by a Site Manager. 
- Feedback types = no. 
  - I see these as core to how the feedback system works, and I don't think we should expose this list for changes.

**Comment by dan-tang-ssd** [comment]
Question:
The score tags CRUD panel use model AdditionalCriteriaScoreTag originally. 
It gives me error 403.
image

After changing to use model ScoreTag, records can be showed in list view.
image

image

Which model should we use...? Is there special needs or reasons to use model AdditionalCriteriaScoreTag here?

**Comment by dan-tang-ssd** [comment]
Question:
Is additional criteria score tag CRUD panel working before...?
It gives me error 405.

image

**Comment by dave-mills** [comment]
> We have a very little chance to add / delete red flags and principles.
> In case we need to add new red flags and principles, is program change required?

I'm pretty sure that those hard-coded `fetch` methods, along with the hard-coded methods on the Assessment Model (`scoreTags1` etc) are no longer used - they were used to populate the Backpack CRUD fields in the assessment, but now we've moved to a custom Vue component those are not used anywhere. 

Which means that changing the list of principles / red flags doesn't need a program change. I actually tested this a couple of weeks ago with the red flagts as the list of red flags had reduced to 10 a while ago (although we didn't get that update until recently). I deleted them from the staging database and everything continued to work smoothly. 

I would suggest that we don't include the Delete Operation on those CRUDs, as we don't have soft deletes on those models and that would result in quite a lot of data loss!

**Comment by dan-tang-ssd** [comment]
Most items are completed. 

Now we have two remaining items:

1. Show admin panel menu items in left hand side, show site-level CRUD panel in right hand side.
Um... how to do that? Do we need to use frameset? Or is there any existing backpack feature we can use to do that quickly...?

2. Delete button throw same error in Score Tag CRUD, Institution types CRUD, Initiative categories CRUD.
I tested that Delete button is working fine in My Institution > Portfolios

image

image

image

**Comment by dan-tang-ssd** [comment]
Added a link to Help Text Entry CRUD in admin panel.
It is not working because help text entry CRUD is in another PR, which has been merged into dev branch.
Suppose the Help Text Entry link in admin panel should be working after merging this PR into dev branch.

image

**Review by dave-mills — APPROVED** [review]
This looks good to me. I documented a few minor issues with required / not-required fields in a few panels (#217), but those are minor enough that they can be fixed later on. 

I think this is good to merge in.

**Comment by dan-tang-ssd** [comment]
Deployment in staging env is completed.
Performed testing with positive result.

image

**Pull request merged**
