### PR TITLE
Add custom assessment criteria

### LINKED ISSUE #40: Add additional assessment dimensions for project assessment

### PR DESCRIPTION
**Pull request by dave-mills**
This PR fixes #40. It adds a new "Custom" `AssessmentCriteria` model. 

- Institutions can create their own assessment Criteria. 
- These are specific to each institution.
- The assessment follows the same process as for each AE Principle, but it's separated into their own page. 
- This is all handled via a new `AssessCustomOperation` trait - cloned from the `AssessOperation` trait and adapted to use the AssessmentCriteria instead of the Principle model. 

NOTE: I suggest merging in the previous #54 first as it'll make it easier to review this branch. 

TODO:

- [x] confirm if custom_score_tags are needed for custom assessment criteria. 
- [x] make ordering of criteria on the assessment page match the custom ordering in the AssessmentCriteriaCrud
- [ ] ~Fix assessment status (right now it's marked as complete if *either* section is done. We need 2 separate statuses to mark when each is complete and then an overall completion status.~

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I checkout dev branch, get latest code. Performed testing successfully for review readlines and assess project.
Then checkout this branch, get latest code. Run migration files.

Below please find my testing result FYI.

Main menu
 - Added new item "Custom Assessment criteria"
 - Another  3 new items at lower left corner, they either return error 404 or 405... do we need to show them in main menu?
image

image

image

image

**Comment by dan-tang-ssd** [comment]
Performed below testing with positive result:
1. Create new additional criteria, with examples
2. Create new additional criteria, without example
3. Reorder additional criteria

A very minor question, should we be consistent in menu item name and CRUD panel name?

image

**Review by dan-tang-ssd — CHANGES_REQUESTED** [review]
Um... some items need to be revised.

**Comment by dave-mills** [comment]
Oops - I somehow managed to put that example / custom example save outside the foreach loop inm the AssessCustomOperation before committing. Thanks for finding that. 

Should be all fixed in the latest commit - tested just now locally and I was able to properly save + retrieve examples + custom examples for multiple additional criteria. 

CleanShot 2023-05-24 at 11 04 01

CleanShot 2023-05-24 at 11 04 05

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I got latest code and run migration files again. Then performed same testings with positive result.
All mentioned items fixed.

I think it is good to merge it into dev branch now.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
