### PR TITLE
Additional criteria view

### PR DESCRIPTION
**Pull request by dave-mills**
This PR generalises the PrincipleAssessment vue components to also work with the Additional Criteria Assessment.

There are some things pending, so I'm calling this a draft PR. @dan-tang-ssd  can you take a look at these? 

- [x] The "complete" status is not being correctly pulled on initial load, which means the completed criteria do not turn green / do not have the score displayed. (The rest of the data seems to be pulled, e.g. the rating, rating_comment and custom_score_tags are all correctly retrieved and displayed when you click into the Modal).
- [x] The finalisation process is not working propertly. It is still hard-linked to the principle-assessment finalisation endpoint, so will need adapting to a different end point that sets the "additional_status" on the assessment.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I executed below commands, the Vue component not showed when assessing additional criteria...

==========

git checkout dev

git pull

==========

git checkout additional-criteria-view

git pull

npm run dev

==========

composer install

npm install

npm run dev

**Comment by dan-tang-ssd** [comment]
Screen shots:

Assess Red Flags and Assess Principles are working fine
image

image

image

image

---

Access Additional Criteria, the Vue component not showed...

image

image

**Comment by dave-mills** [comment]
I've updated this PR so the vue component should now render, and made a few additional tweaks to fix some issues with the save / finalise workflow.

**Comment by dan-tang-ssd** [comment]
As I have only one additional assessment criteria in my local env, I would like to add some more for testing.

When I add / edit additional assessment criteria, below error occurred...

image

image

**Comment by dave-mills** [comment]
> When I add / edit additional assessment criteria, below error occurred...

Fixed in the latest commit. The issue was with my change in relationship name. (I made the `AdditionalCriteria->scoreTags()` name match the `AssessmentPrinciple` class so we could use the same name in the Vue component. I'd found all the main references, but PHPStorm didn't find the one hidden in the string name of the CRUD field).

**Comment by dave-mills** [comment]
> Just one minor issue about "Discard Changes" button. It updates the value in front end.

I believe this issue is fixed in #134, so I wouldn't worry about it here.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
