### PR TITLE
Extra institution + portfolio details

### LINKED ISSUE #146: Add required details to institution and portfolios
From the tech spec:

An institution has the following information:
-	Name (required)
-	Institution type: selected from NGO, Government, University, For-profit corporation, other (optional)
o	The list of institution types will be confirmed in discussion with the Agroecology Coalition.
-	Which country is the Institution HQ based? (optional)
-	What is the geographic reach of the institution? (country(ies), multi-country, regional) (optional)
-	Description (optional)

### PR DESCRIPTION
**Pull request by dave-mills**
fixes #146.

This PR adds the required extra information to portfolios and organisations, as per the technical specification.

### Updates
- The database + seeders / factories are updated with the new fields
- The portfolio table view now includes budget and geographic reach
- Creating / editing portfolios via the CRUD panel controller has the extra fields:
  - NOTE: I chose to only allow portfolio budgets in the institution's default currency, for simplicity. Given we do not have a clear start date for a portfolio (as with an initiative), I don't know how much sense it would be to give a single exchange rate for conversion. If this becomes an issue,  I think it is a V2.0 feature. 

- Editing institution details is now via a Vue component, and includes the extra relevant fields. 
- Users without the "edit own institution" permission will see the fields as disabled. 

The tech specs were not fully clear on whether institutions and portfolios should be linkable to continents/regions/countries. I chose to not do this, but am open to this being a requested feature if it is deemed to be vital. 

This PR also adds InstitutionType as a new data model, linked to institutions.

### CODE REVIEW

**Comment by dave-mills** [comment]
NOTE: on merge, we should run the InstitutionTypeSeeder on the live site to setup the list of institution types.

**Comment by dan-tang-ssd** [comment]
Institution Settings
Fill in optional information, click "Save" button

image

Um... optional information not saved...
image

Checked database, optioanl information not saved into database
image

**Comment by dan-tang-ssd** [comment]
> NOTE: on merge, we should run the InstitutionTypeSeeder on the live site to setup the list of institution types.

I have executed InitiativeCategorySeeder and InstitutionTypeSeeder for initial data loading in local env.

**Comment by dan-tang-ssd** [comment]
Create a new portfolio, fill in a very big budget, save, success

image

image

Edit the newly created portfolio, change to a even bigger budget, overflow.
Um... should we check budget for the maximum value?

image

image

**Comment by dan-tang-ssd** [comment]
Performed testing with positive result:
1. New initiative can be saved
2. Settings > Optional Information can be saved

Added validation to check for maximum value of portfolio budget, i.e. 18446744073709551615.

Screen shots:

Error message showed if portfolio budget > 18446744073709551615
image

The maximum portfolio budget is 18446744073709551615
image

image

**Review by dan-tang-ssd — APPROVED** [review]

**Comment by dave-mills** [comment]
@dan-tang-ssd thanks :)

**Pull request merged**
