### PR TITLE
Add soft delete

### LINKED ISSUE #113: Add an option to delete initiative and portfolios
**Is your feature request related to a problem? Please describe.**
Currently there is no option to delete an initiative. We need to be able to delete an initiative from a portfolio.

**Describe the solution you'd like**
Add delete button in Initiatives.

**Describe alternatives you've considered**
Um... no alternatives...

**Additional context**
We need this feature to remove double entry or testing data for initiatives.

image

Related email:
[Comments by GIZ - AW Agroecology Funding Portfolio Assessment Tool - Invitation.zip](https://github.com/stats4sd/aec_portfolio/files/11956416/Comments.by.GIZ.-.AW.Agroecology.Funding.Portfolio.Assessment.Tool.-.Invitation.zip)

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR fixes #113 .

This is submitted for adding soft-delete to portfolios and projects. It also add ON DELETE CASCADE ON UPDATE CASCADE for projects.portfolio_id.

There are two remaining items:
1. After confirming to remove a portfolio, it shows a white page with a "1". Suppose it should divert to portfolios page.
2. I do not know how to add a working "Remove Initiative" button in Vue component.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I am trying to add a "Remove Initiative" button, both buttons are not working yet...

image

image

**Comment by dave-mills** [comment]
@dan-tang-ssd I've updated the vue component. I used a trick we've used in the past, where the 'prop' becomes the "initial" read-only version of a property, and onMount() it's set to a reactive variable. Looks like it's working ok now.

**Comment by dan-tang-ssd** [comment]
It works well. That's great.
Thank you Dave.

**Review by dave-mills — APPROVED** [review]
Looks good to go 👍

**Comment by dan-tang-ssd** [comment]
Live env deployment is completed.
A quick hot fix is deployed shortly to resolve duplicate import statement issue.

Performed testing in with positive result in live env.
An initiative can be removed now.

**Pull request merged**
