### PR TITLE
Store user selected portfolio in session

### LINKED ISSUE #111: [BUG] All initiatives showed after accessing red flags even user selected a portfolio at the beginning
**Describe the bug**
All initiatives showed after accessing red flags even user selected a portfolio at the beginning

**To Reproduce**
My Institution > A new portfolio > SHOW INITIATIVES > Initiative ABC > Click Assess Red Flags button > Save > 
Show all initiatives instead of showing initiative of selected portfolio

**Expected behavior**
After saving red flags assessment, show initiatives of selected portfolio only.

**Screenshots**

image

image

image

image

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR fixes #111.

User can select a portfolio by below action:
My Institution > click "SHOW INITIATIVES" button of a portfolio

The corresponding portfolio is considered as user selected portfolio.
When user clicks "Initiatives", initiative page will only show all initiatives of the selected portfolio.

User can reset the selected portfolio by clicking "My Institution", as this action means user wants to select another portfolio.

By the way, I would expect this handling may create user confusion.
Some users may select a portfolio, then keep clicking "Initiatives" and asking where are my other initiatives...

---

Screen shots:

Select a portfolio
image

Assess red flags for one of the initiatives
image

Finish assessing red flags
image

Initiatives page shows initiatives of user selected portfolio only
image

### CODE REVIEW

**Comment by dave-mills** [comment]
>By the way, I would expect this handling may create user confusion.
>Some users may select a portfolio, then keep clicking "Initiatives" and asking where are my other initiatives...

Perhaps, though here we're addressing requests from some users who were confused that this filter was *not* retained, so swings and roundabouts, perhaps. 

I'm currently considering options to retain *all* the filters and searches, due to various pieces of feedback I've received. See - #140. Perhaps including a "current active filters" section just above the list, and highlighting the "remove filter" or "reset" options would help with this potential confusion?

**Comment by dan-tang-ssd** [comment]
> I'm currently considering options to retain _all_ the filters and searches, due to various pieces of feedback I've received. See - #140. Perhaps including a "current active filters" section just above the list, and highlighting the "remove filter" or "reset" options would help with this potential confusion?

OK, let me do some changes to tackle #140.

**Comment by dan-tang-ssd** [comment]
The program change is 90% ready, just remain the last bit about setting integer value for sortDir...

---

The Vue component now sends ajax call to store settings in session when any settings changed.

Stored settings in session will be retrieved and applied in Vue component when user enter initiative page.

By clicking "Reset" link, user can reset all settings in Vue component and also in session.

In "My Institution" > portfolio list > click "SHOW INITIATIVES" button, it will reset all settings but only keep user selected portfolio in settings.

**Comment by dan-tang-ssd** [comment]
The last bit is completed. Now integer type parameter "sortDir" works properly.

This is now ready for review.

**Comment by dan-tang-ssd** [comment]
Screen shots:

Login, go to Initiatives page directly
image

Sort by name in ascending order, by default
All other filters are empty
image

Change sorting to Descending
Enter search string as "aa"
Then go to "My Institution" page
image

Do nothing, go back to "Initiatives" page
image

Previous settings are kept and applied
image

**Comment by dan-tang-ssd** [comment]
Click "Reset" link to reset all settings
image

All settings removed and reset to default values
image

**Comment by dan-tang-ssd** [comment]
Apply all settings
Then go to "My Institution" page
image

Go to "Initiatives" page
image

All settings kept and applied
image

Go to "My Institution" page
Click "SHOW INITIATIVES" button of one of the portfolios
image

All previous settings are reset
Only apply portfolioFilter to show all initiatives of selected portfolio
image

**Comment by dave-mills** [comment]
Looks like some merge issues here - this branch overwrote all the changes to InitiativesList.vue from #139. I've added them back in here.

**Review by dave-mills — CHANGES_REQUESTED** [review]
I think this is a really nice feature / use of the Session Storage in Laravel. It's very nice to leave the Initiatives list and then return to it in the same state that I left it. 

I noticed that while typing in the search bar, a request was being sent every time I typed a letter, which could easily lead to an overwhelming number of requests. To avoid that, I refactored that slightly to use watchDebounced() to manage the session storage requests. 

One other issue I've noticed is that when clicking "back" in the browser, the filter parameters are not kept, which I think is because we're loading the parameters back from the query-string instead of getting from session storage again. 

Looking again at the code, I find it's unclear when the session storage is referenced and when the url query parameters are referenced. My overall recommendation is to remove the reliance / use of URL Query params entirely and just use the session storage, which would probably simplify the code logic a lot and fix the issue I mention above about the "back" button.

**Review by dave-mills — APPROVED** [review]
Looks good and works well - The sort/filter/search is retained whenever I return to the initiatives list page, no matter how I reach that page (page link, back button in browser, manually typing in the url). 

I added a small piece to handle the specific instance when the user clicks on the "show initiatives" button for a specific portfolio, i.e. when the url has a `portfolioFilter` query parameter. 

This looks good to go 👍

**Pull request merged**
