### PR TITLE
Live Env Deployment

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
Hi Dave,

This PR contains many program changes since Jan 2024. 

I am not quite sure which option we should go now, would you kindly advise?
1. Deploy all program changes to live env, perform testing to confirm everything changed is working fine
   - Many changes to list here, please refer to "Commits" section of this PR for details
2. Only deploy the bug fix in branch "fix-dashboard-unexpected-message" (checkout main branch then make delta change)
   - Resolve the unexpected message
   - Exclude previously completed assessments in dashboard

### CODE REVIEW

**Comment by dave-mills** [comment]
Looking at the staging site, this seems to work well for creating / editing initiatives. I think this is good to publish. 

Once this is deployed, we still have some pending items: 

1. We need to fill the gaps in the exchange rates table. Probably the easiest approach is to do this 'manually' in a local version, and then copy the results to live. 
2. After that, we will need to run the command to add the "budget_eur" and "exchange_rate_eur" to all existing projects.

**Comment by dan-tang-ssd** [comment]
> One note - this will break the budget filters on the dashboard until all existing projects have a budget_eur value.
> 
> I suggest we prepare the database table of legacy exchange rates before merging this, so we can then:
> 
>     * merge this PR and deploy to live
> 
>     * update the exchange_rates table with daily exchange rates for every day from now back till... Jan 01 2011 (the earliest date for real existing projects).
> 
>     * run the command to populate budget_eur
> 
> 
> ... at pretty much the same time.

Thank you Dave.
Yes, it sounds great.

I will start to retrieve historical exchange rates year by year in my local env first.
I will keep you update for progress.

**Comment by dave-mills** [comment]
> Question: if a project has not started yet, how do users assess it...?

The assessment is about how well the project aligns with AE principles, which can be done based on the project proposal or plan. Often, this is the way people will assess portfolios and budgets, and then they might do another assessment during or after the project to explore how AE-aligned the project *actually* was.

**Review by dave-mills — APPROVED** [review]
Looks good to me. Seems like we're ready to deploy. Sounds sensible to do the deployment tomorrow morning, so we're available in case of issues.

**Comment by dan-tang-ssd** [comment]
Live env deployment is completed.
Manually run command to calculate projects.budget_eur and projects.exchange_rate_eur.
Performed testing in dashboard with positive testing result.

**Pull request merged**
